2+3

In [1]:
2+3

5

In [2]:
x=2

In [3]:
y=5

In [4]:
x+y

7

In [5]:
def number_of_lines():
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    inp = fhand.read()
    fhand.close()
    count=0
    for c in inp:
        if c == '\n':
            count +=1
    return count

In [6]:
number_of_lines()

1910

In [7]:
def count_number_of_lines():
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    count = 0
    for line in fhand:
        line = line.rstrip() # Remove new line characters from right
        if line.startswith('From:'):
            count +=1
            #print(line)
    return count

In [8]:
count_number_of_lines()

27

In [9]:
def average_spam_confidence():
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    count=0
    spm_Conf_avg=0.0
    for line in fhand:
        line = line.rstrip() # Remove new line characters from right
        if line.startswith ('X-DSPAM-Confidence:'):
            spm_Conf=line.split(':')
            spm_Conf_avg += float(spm_Conf[1])
            count +=1
    return (spm_Conf_avg/count)

In [10]:
average_spam_confidence()

0.7507185185185187

In [11]:
def find_email_sent_days():
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    thisdict={}
    for line in fhand:
        line = line.rstrip() # Remove new line characters from right
        if line.startswith('From'):
            #print (line)
            arr_with_tab_split = line.split(' ')
            if len (arr_with_tab_split) >3:
                day_of_the_week = arr_with_tab_split[2]
                if day_of_the_week in thisdict:
                    thisdict[day_of_the_week] += 1
                else:
                    thisdict[day_of_the_week] =1

    return thisdict
            

In [12]:
find_email_sent_days()

{'Sat': 1, 'Fri': 20, 'Thu': 6}

In [13]:
def count_message_from_email():
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    thisdict={}
    for line in fhand:
        line = line.rstrip() # Remove new line characters from right
        if line.startswith('From:'):
            #print (line)
            arr_with_tab_split = line.split(' ')
            from_email_add = arr_with_tab_split[1]
            if from_email_add in thisdict:
                thisdict[from_email_add]+=1
            else:
                thisdict[from_email_add]=1
    return thisdict
        

In [14]:
count_message_from_email()

{'stephen.marquard@uct.ac.za': 2,
 'louis@media.berkeley.edu': 3,
 'zqian@umich.edu': 4,
 'rjlowe@iupui.edu': 2,
 'cwen@iupui.edu': 5,
 'gsilver@umich.edu': 3,
 'wagnermr@iupui.edu': 1,
 'antranig@caret.cam.ac.uk': 1,
 'gopal.ramasammycook@gmail.com': 1,
 'david.horwitz@uct.ac.za': 4,
 'ray@media.berkeley.edu': 1}

In [15]:
def count_message_from_domain():
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    thisdict={}
    for line in fhand:
        line = line.rstrip() # Remove new line characters from right
        if line.startswith('From:'):
            #print (line)
            arr_with_split = line.split('@')
            from_email_domain = arr_with_split[1]
            if from_email_domain in thisdict:
                thisdict[from_email_domain]+=1
            else:
                thisdict[from_email_domain]=1
            
    return thisdict

In [16]:
count_message_from_domain()

{'uct.ac.za': 6,
 'media.berkeley.edu': 4,
 'umich.edu': 7,
 'iupui.edu': 8,
 'caret.cam.ac.uk': 1,
 'gmail.com': 1}

In [17]:
import numpy as np

In [18]:
x = np.zeros((3,4))
print (x)
type (x.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


numpy.dtype

In [19]:
np.linspace(0,100,9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [20]:
np.linspace(0,10,25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [21]:
a = np.array([1,5,3,19.7,3])
print(a[1])
print(a[2:4])

5.0
[ 3.  19.7]


In [22]:
x = np.random.rand(5,8)
x

array([[0.57894858, 0.65235744, 0.18376237, 0.61628057, 0.18338628,
        0.46077423, 0.71089127, 0.57595984],
       [0.89709813, 0.80773395, 0.98693738, 0.44447746, 0.68858723,
        0.14872298, 0.26508556, 0.77602447],
       [0.72781058, 0.58705167, 0.9125325 , 0.54075813, 0.41787939,
        0.39468111, 0.96691744, 0.65218167],
       [0.36560136, 0.46345769, 0.28629056, 0.67399548, 0.85905349,
        0.73281826, 0.44439674, 0.88766842],
       [0.33116723, 0.29416029, 0.73188994, 0.53620894, 0.46347333,
        0.18528265, 0.47708675, 0.5191791 ]])

In [23]:
print(x[1])
print("x one-one is:",x[1,1])
print ("Getting a slice of the array")
print (x[0:2, 0:2])

[0.89709813 0.80773395 0.98693738 0.44447746 0.68858723 0.14872298
 0.26508556 0.77602447]
x one-one is: 0.807733951052926
Getting a slice of the array
[[0.57894858 0.65235744]
 [0.89709813 0.80773395]]


In [24]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
sample_list = [1,2,3]
list_array = np.array(sample_list)
print (list_array)

[1 2 3]


In [26]:
tup = (1,2,3)
my_tup_array = np.array(tup)
print (my_tup_array)

[1 2 3]


In [27]:
def multiply_loops(A, B):
    c=np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for k in range(B.shape[1]):
            c[i,k] = 0
            for j in range(B.shape[0]):
                n = A[i,j] * B[j,k]
                c[i,k] += n
    return c

In [28]:
def multiply_vector(A, B):
     return A @ B

In [29]:
X = np.random.random((100, 100))
Y = np.random.random((100, 100))

In [30]:
%timeit multiply_loops(X, Y)
%timeit multiply_vector(X, Y)

874 ms ± 95.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
28.7 µs ± 1.14 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [31]:
tup_dim = (3,4)
my_zeros_array = np.zeros(tup_dim, dtype=np.int16)
my_ones_array = np.ones(tup_dim, dtype=np.int16)
my_seven_array = np.full(tup_dim,7, dtype=np.int16)
my_identity_array = np.identity(4, dtype=np.float64)

print (my_zeros_array)
print (my_ones_array)
print (my_seven_array)
print (my_identity_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
my_rand_array = np.random.rand(3,4)
my_rand_array

array([[0.68637768, 0.90155269, 0.38061239, 0.80996982],
       [0.85072575, 0.9682958 , 0.20355537, 0.44409823],
       [0.72670303, 0.65265339, 0.85041601, 0.53286717]])

In [33]:
tup_dim = (3,4)
my_uninitialized_array = np.empty(tup_dim)
my_uninitialized_array

array([[0.68637768, 0.90155269, 0.38061239, 0.80996982],
       [0.85072575, 0.9682958 , 0.20355537, 0.44409823],
       [0.72670303, 0.65265339, 0.85041601, 0.53286717]])

In [34]:
my_range_array = np.arange (10,30,5)
my_range_array

array([10, 15, 20, 25])

In [35]:
my_spaced_array =np.linspace(0,5/3,6)
my_spaced_array

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [36]:
array_A = np.array([ [3,4,6], [0,8,1]])
print (array_A)
print ("Dimensions: ", array_A.ndim)
print ("Shape: " ,array_A.shape)
print ("Size: ", array_A.size)
print ("Dtype: ", array_A.dtype)
print ("Itemsize: ", array_A.itemsize)

[[3 4 6]
 [0 8 1]]
Dimensions:  2
Shape:  (2, 3)
Size:  6
Dtype:  int64
Itemsize:  8


In [37]:
my_array = np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])
print(my_array)
print ("Dimensions: ", my_array.ndim)
print ("Shape: " ,my_array.shape)
print ("Size: ", my_array.size)
print ("Dtype: ", my_array.dtype)
print ("Itemsize: ", my_array.itemsize)

[[ 1  4  5  6]
 [ 7  8  9 10]
 [11 12 14 16]]
Dimensions:  2
Shape:  (3, 4)
Size:  12
Dtype:  int64
Itemsize:  8


In [38]:
import os
import pandas as pd
# defining housing.csv file path
HOUSING_PATH = '../ml/machine_learning/datasets/housing/'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)

In [39]:
my_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [40]:
my_df.describe()

longitude   latitude  housing_median_age  total_rooms  total_bedrooms  \
count    5.000000   5.000000            5.000000     5.000000        5.000000   
mean  -122.238000  37.858000           43.600000  2469.400000      388.000000   
std      0.013038   0.013038           13.501852  2603.018114      405.241286   
min   -122.250000  37.850000           21.000000   880.000000      129.000000   
25%   -122.250000  37.850000           41.000000  1274.000000      190.000000   
50%   -122.240000  37.850000           52.000000  1467.000000      235.000000   
75%   -122.230000  37.860000           52.000000  1627.000000      280.000000   
max   -122.220000  37.880000           52.000000  7099.000000     1106.000000   

        population   households  median_income  median_house_value  
count     5.000000     5.000000       5.000000            5.000000  
mean    868.400000   383.800000       6.674660       369340.000000  
std     862.336535   424.493463       1.921878        47089.733488  
min     322.000000   126.000000       3.846200       341300.000000  
25%     496.000000   177.000000       5.643100       342200.000000  
50%     558.000000   219.000000       7.257400       352100.000000  
75%     565.000000   259.000000       8.301400       358500.000000  
max    2401.000000  1138.000000       8.325200       452600.000000

In [41]:
my_df.size

50

In [42]:
FILE = "housing_short.csv"

In [43]:
def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)

In [44]:
longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

In [45]:
print (median_house_value_arr)

[452600. 358500. 352100. 341300. 342200.]


In [46]:
print (HOUSING_PATH)

../ml/machine_learning/datasets/housing/


In [47]:
FILE = os.path.join(HOUSING_PATH, "housing.csv")

In [48]:
def load_housing_dataset (file =FILE ):
    return np.genfromtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skip_header=1, filling_values = 99999999, unpack=False)

In [49]:
result_arr = load_housing_dataset()

In [50]:
print (result_arr)

[(-122.23, 37.88, 41.,  880.,  129.,  322.,  126., 8.3252, 452600., b'NEAR BAY')
 (-122.22, 37.86, 21., 7099., 1106., 2401., 1138., 8.3014, 358500., b'NEAR BAY')
 (-122.24, 37.85, 52., 1467.,  190.,  496.,  177., 7.2574, 352100., b'NEAR BAY')
 ...
 (-121.22, 39.43, 17., 2254.,  485., 1007.,  433., 1.7   ,  92300., b'INLAND')
 (-121.32, 39.43, 18., 1860.,  409.,  741.,  349., 1.8672,  84700., b'INLAND')
 (-121.24, 39.37, 16., 2785.,  616., 1387.,  530., 2.3886,  89400., b'INLAND')]


In [51]:

my_arr_1 = np.array([ [0,1], [2,3] ])
print (my_arr_1)

my_arr_1.resize( (2, 3) )  # need two rows and one column

print(my_arr_1)

[[0 1]
 [2 3]]
[[0 1 2]
 [3 0 0]]


In [52]:
my_arr = np.array([[1,2,3,4],[5,6,7,8]])
print(my_arr)
my_arr.resize((3,4))
print (my_arr)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [0 0 0 0]]


In [53]:
my_first_arr = np.array([-1,2,3,4,5,6,7,8])
my_first_arr

array([-1,  2,  3,  4,  5,  6,  7,  8])

In [54]:
my_new_arr = my_first_arr.reshape(2,4)
print (my_new_arr)
print (my_first_arr)

[[-1  2  3  4]
 [ 5  6  7  8]]
[-1  2  3  4  5  6  7  8]


In [55]:
my_second_arr = np.array([0,1,2,3,4,5,6,7,8])
print(my_second_arr)
my_updated_arr = my_second_arr.reshape(-1,3)
print (my_updated_arr)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
my_orig_arr = np.array([1,15,3,9,26,7,89,12])
my_rev_arr = my_orig_arr[::-1]
print (my_rev_arr)

[12 89  7 26  9  3 15  1]


In [57]:
my_orig_arr2 = np.array([2,9,17,13,1,4,20,57])
my_orig_arr2[2:5] = -6
print (my_orig_arr2)

[ 2  9 -6 -6 -6  4 20 57]


In [58]:
apple = np.array([1,8,23,3,18,91,7,15])
apple_slice = apple[1:4]
print (apple_slice)
print (apple)

[ 8 23  3]
[ 1  8 23  3 18 91  7 15]


In [59]:
apple_slice[1] =9999
print (apple_slice)
print (apple)

[   8 9999    3]
[   1    8 9999    3   18   91    7   15]


In [60]:
apple_slice_new = apple[2:5].copy()
apple_slice_new[1]=2222
print (apple_slice_new)
print (apple)

[9999 2222   18]
[   1    8 9999    3   18   91    7   15]


In [61]:
from sklearn.datasets import load_sample_image

In [62]:
china = load_sample_image("china.jpg")
print (china)

[[[174 201 231]
  [174 201 231]
  [174 201 231]
  ...
  [250 251 255]
  [250 251 255]
  [250 251 255]]

 [[172 199 229]
  [173 200 230]
  [173 200 230]
  ...
  [251 252 255]
  [251 252 255]
  [251 252 255]]

 [[174 201 231]
  [174 201 231]
  [174 201 231]
  ...
  [252 253 255]
  [252 253 255]
  [252 253 255]]

 ...

 [[ 88  80   7]
  [147 138  69]
  [122 116  38]
  ...
  [ 39  42  33]
  [  8  14   2]
  [  6  12   0]]

 [[122 112  41]
  [129 120  53]
  [118 112  36]
  ...
  [  9  12   3]
  [  9  15   3]
  [ 16  24   9]]

 [[116 103  35]
  [104  93  31]
  [108 102  28]
  ...
  [ 43  49  39]
  [ 13  21   6]
  [ 15  24   7]]]


In [63]:
portion = china [120:250,110:230]
print (portion)

[[[ 62  61  56]
  [ 25  22  15]
  [ 28  29  21]
  ...
  [ 21  27  23]
  [ 25  25  23]
  [ 18  13  10]]

 [[ 33  34  29]
  [ 24  24  16]
  [ 38  39  33]
  ...
  [ 21  25  24]
  [ 26  24  25]
  [ 29  23  25]]

 [[  3   3   1]
  [ 15  14  10]
  [ 29  30  25]
  ...
  [ 30  31  33]
  [ 18  16  19]
  [ 20  15  19]]

 ...

 [[ 35  32  25]
  [ 32  32  24]
  [ 28  22  22]
  ...
  [ 70  81  85]
  [ 76  88  86]
  [ 93  86  68]]

 [[ 52  51  33]
  [ 52  46  20]
  [ 50  43  25]
  ...
  [ 72  76  88]
  [ 94  99 105]
  [122 104  84]]

 [[ 58  60  39]
  [ 63  62  34]
  [ 65  67  46]
  ...
  [ 90 104 105]
  [103 119 119]
  [127 126 108]]]


In [64]:
china.shape

(427, 640, 3)

In [68]:
image = china[150:220, 130:250]
image.shape

(70, 120, 3)

In [69]:
height, width, channels = image.shape

In [70]:
image_grayscale = image.mean(axis=2).astype(np.float32)

In [71]:
image_grayscale.shape

(70, 120)

In [76]:
images = image_grayscale.reshape(1,height,width,1)


In [77]:
images.ndim

4

In [86]:
multi_arr = np.arange(12).reshape(3,4)
print (multi_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [89]:
rows_wanted = np.array( [True, False, True] )
print (rows_wanted)
multi_arr_portion = multi_arr[rows_wanted,:]
print (multi_arr_portion)

[ True False  True]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [90]:
my_multi_arr = np.arange(20).reshape(4,5)
print (my_multi_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [91]:
my_multi_arr_portion = my_multi_arr[2:4,2:5]
print (my_multi_arr_portion)

[[12 13 14]
 [17 18 19]]


In [98]:
my_2d_arr = np.arange(20).reshape(4,5)
my_1d_arr = my_2d_arr.ravel()
print (my_1d_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [106]:
import numpy as np
a = np.array([ 20, 30, 40, 50])
b = np.arange(4)
c=a+b
print (c)

[20 31 42 53]


In [107]:
f = a-b
print (f)

[20 29 38 47]


In [131]:
d_arr = np.array([60,70,80,90])
e_arr = np.arange(4)
f_arr = d_arr - e_arr
print (f_arr)

[60 69 78 87]


In [152]:
# ARRAY MULTIPLICATION (* & dot PRODUCT)

In [154]:
A_arr = np.array([ [ 5,9], [4, 7] ])
B_arr = np.array( [ [2, 8], [1, 6] ] )

In [156]:
M_arr = A_arr * B_arr
print (M_arr)

[[10 72]
 [ 4 42]]


In [158]:
C_arr = np.array([ [ 5,9], [4, 7] ])
D_arr = np.array( [ [2, 8], [1, 6] ] )
P_arr = np.dot(C_arr,D_arr)
print (P_arr)

[[19 94]
 [15 74]]


In [178]:
R = np.array( [ 20, 30, 40, 50] )
S = np.arange( 1, 5 )
T = R / S
Ti = R // S
Tm = R % S
print (R)
print (S)
print ("Division:" , T)
print ("Integer Division:", Ti)
print ("Modulus:",Tm)

[20 30 40 50]
[1 2 3 4]
Division: [20.         15.         13.33333333 12.5       ]
Integer Division: [20 15 13 12]
Modulus: [0 0 1 2]


In [185]:
R_div = np.array([ [ 25,65], [40, 14] ])
S_div = np.array([ [2, 10], [4, 5] ] )
T_div = R_div / S_div
print ("Simple Divison:", T_div)


R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array([ [2, 10], [8, 3] ] )
T_int_div = R_int_div // S_int_div
print ("Integer Division:", T_int_div)


R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array([ [2, 10], [8, 3] ] )
T_mod = R_mod % S_mod
print ("Modulus:", T_mod)

Simple Divison: [[12.5  6.5]
 [10.   2.8]]
Integer Division: [[12  6]
 [ 5 23]]
Modulus: [[0 5]
 [0 1]]


In [204]:
R_exp = np.array( [ 20, 30, 40, 50] )
S_exp = np.arange( 1, 5 )
T_exp = R_exp ** S_exp 
print(R_exp)
print(S_exp)
print(T_exp)

[20 30 40 50]
[1 2 3 4]
[     20     900   64000 6250000]


In [205]:
R_exp = np.array([ [ 4, 2], [3, 4 ] ] )
S_exp = np.array( [ [2, 10], [4, 5] ] )
T_exp = R_exp ** S_exp
print (T_exp)

[[  16 1024]
 [  81 1024]]


In [215]:
m = np.array( [ 20, -5, 30, 40] )
print (m < [15, 16, 35, 36])
print (m[m<25])

[False  True  True False]
[20 -5]


In [218]:
U = np.array([ [ 22, 45], [90, 4 ] ] )
print (U)
print (U[U<45])

[[22 45]
 [90  4]]
[22  4]


In [223]:
X = np.array( [ [-2.5, 3.1, 7],
                [10, 11, 12] ] )
print("mean = ", X.mean())
print("Variance = ", X.var())
print("Standard Deviation = ", X.std())
print("min = ", X.min())
print("max = ", X.max())
print("sum = ", X.sum())
print("product = ", X.prod())

mean =  6.766666666666667
Variance =  25.855555555555554
Standard Deviation =  5.084835843520964
min =  -2.5
max =  12.0
sum =  40.6
product =  -71610.0


In [229]:
X_stat = np.array ([ [ 1, 2, 3], [ 4, -5, 6] ])
print("mean = ", X_stat.mean())
print("Variance = ", X_stat.var())
print("Standard Deviation = ", X_stat.std())
print("min = ", X_stat.min())
print("max = ", X_stat.max())
print("sum = ", X_stat.sum())
print("product = ", X_stat.prod())

mean =  1.8333333333333333
Variance =  11.805555555555557
Standard Deviation =  3.435921354681384
min =  -5
max =  6
sum =  11
product =  -720


In [241]:
Y = np.arange(24).reshape(2,3,4)

print(Y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [249]:
Z = np.arange(18).reshape(2,3,3)
print (Z)
print( "Sum axis=0:\n", Z.sum(axis=0))
print( "Sum axis=1:\n", Z.sum(axis=1))
print( "Sum axis=2:\n", Z.sum(axis=2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
Sum axis=0:
 [[ 9 11 13]
 [15 17 19]
 [21 23 25]]
Sum axis=1:
 [[ 9 12 15]
 [36 39 42]]
Sum axis=2:
 [[ 3 12 21]
 [30 39 48]]


In [ ]:
N= np.arange(6).reshape(3,2)
print (N)
print("Transpose = ", N.T)

In [270]:
X_broad = np.ones((3,3))
Y_broad = np.arange(3)
Z_broad = X_broad + Y_broad
print (X_broad)
print (Y_broad)
print (Z_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
